language: go
go:
  - 1.8
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
jobs:
  include:
    - stage: test
      script: make build test
    - stage: deploy
      script: make release
