language: go
go:
  - 1.8
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
jobs:
  include:
    - stage: test
      script: make build test && sudo $(which go) test -v ./cmd/cni-vpcnet/ -vethtests
      sudo: true
    - stage: deploy
      script: make release
