language: go
go:
  - 1.9
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
jobs:
  include:
    - stage: test
      script: make build test && sudo $(which go) test -v ./pkg/ifmgr -allow-netns
      sudo: true
    - stage: deploy
      script: make release
