required = [
  "github.com/containernetworking/plugins/plugins/main/loopback",
  "github.com/containernetworking/plugins/plugins/main/ptp",
  "github.com/golang/protobuf/protoc-gen-go",
]


ignored = [
  "golang.org/x/exp/inotify", # Doesn't build on Mac, shouldn't need it anyway
]

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.45"

[[constraint]]
  name = "github.com/cenk/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "~0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "~0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/j-keck/arping"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/songgao/packets"

[[constraint]]
  branch = "master"
  name = "github.com/songgao/water"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.8.5"

[[constraint]]
  branch = "master"
  name = "k8s.io/utils"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.8.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "~1.0.0"

## Things for client-go

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

# Fix vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

# Fix vendor/k8s.io/kubernetes/pkg/kubelet/cm/util/cgroups_linux.go:65:19: undefined: cgroups.GetOwnCgroup
[[override]]
  name = "github.com/opencontainers/runc"
  revision = "4d6e6720a7c885c37b4cb083c0d372dda3425120"

# logrus casing
[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"

# Fix Solving failure: package github.com/docker/docker/api/types/reference does not exist within project github.com/docker/docker
[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"